# Generated by Django 3.2.4 on 2021-06-17 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20210617_1937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
